# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python: 3.6-dev
sudo: required

cache:
  directories:
    - eggs
install:
  - pip3.6 install -e .[test]
script:
  - bin/py.test -s --cov=guillotina_rediscache -v --cov-report term-missing guillotina_rediscache
after_success:
  - pip install coveralls
  - coveralls
